app_name         = "JwSemanticSearcher"
location         = "East US 2"
location_short   = "eus2"
environment_name = "dev"
common_tags = {
  Environment = "development"
  Project     = "JW Semantic Searcher"
  Owner       = "Cobollatin"
  CreatedBy   = "Terraform"
  Location    = "East US 2"
}
swa_repository              = "jw-semantic-searcher"
acr_repositories            = ["jw-semantic-searcher"]
batch_repositories          = ["jw-semantic-searcher"]
batch_docker_images         = ["indexer"]
indexer_name                = "indexer"
semantic_search_config_name = "semantic-search-config"
openai_model                = "text-embedding-3-small"
openai_project_name         = "jw-semantic-search"
openai_project_id           = "proj_z02T1LalUIoCPlZqeuFzl5CK"
openai_org_name             = "Personal"
openai_org_id               = "org-FrSwBIfTy6cbV0sOmjkZyKYY"
