name: Azure ACR retention policy
on:
    schedule:
        - cron: "0 0 * * *"
permissions:
    contents: read
    id-token: write
    packages: read
env:
    IMAGE_NAME: "indexer"
    IMAGE_TAG: ${{ github.sha }}
jobs:
    acr_retention:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4.1.4
            - uses: azure/login@v2.1.0
              name: Azure login
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}
            - name: Set ACR retention policy
              run: az acr repository update --name ${{ secrets.AZURE_CONTAINER_REGISTRY }} --image ${{ env.IMAGE_NAME }} --retention 7
