name: Azure Batch CI/CD
run-name: "Azure Batch CI/CD for commit ${{ github.sha }}"
on:
    push:
        branches:
            - main
        paths:
            - "indexer/**"
            - ".github/workflows/batch_pipeline.yaml"
    pull_request:
        types: [opened, synchronize, reopened, closed]
        branches:
            - main
        paths:
            - "indexer/**"
            - ".github/workflows/batch_pipeline.yaml"
permissions:
    contents: read
    id-token: write
    packages: read
env:
    IMAGE_NAME: "indexer"
    IMAGE_TAG: ${{ github.sha }}
jobs:
    indexer_ci:
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request' && github.event.action != 'closed'
        steps:
            - uses: actions/checkout@v4.1.4
            - name: "Do nothing"
              run: echo "Doing nothing for now"
    buildImage:
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        steps:
            - uses: actions/checkout@v4.1.4
            - uses: azure/login@v2.1.0
              name: Azure login
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}
            - name: Build and push image to ACR
              run: az acr build --image ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} --image ${{ env.IMAGE_NAME }}:latest --registry ${{ secrets.AZURE_CONTAINER_REGISTRY }} -g ${{ secrets.ACR_RESOURCE_GROUP }} -f ./indexer/Dockerfile ./indexer
    deploy:
        runs-on: ubuntu-latest
        needs: buildImage
        steps:
            - uses: actions/checkout@v3
            - uses: azure/login@v2.1.0
              name: Azure login
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}
            - name: Deploy to Azure Batch
              run: az batch task create --task-id ${{ github.sha }} --job-id ${{ secrets.BATCH_JOB_ID }} --account-endpoint ${{ secrets.BATCH_ACCOUNT_ENDPOINT }} --account-key ${{ secrets.BATCH_ACCOUNT_KEY }} --account-name ${{ secrets.BATCH_ACCOUNT_NAME }} --command-line "echo 'Hello World from $env'"

