name: Azure Static Web Apps CI/CD
run-name: "Azure Static Web Apps CI/CD for commit ${{ github.sha }}"
on:
    push:
        branches:
            - main
        paths:
            - "webapp/**"
            - "api/**"
    pull_request:
        types: [opened, synchronize, reopened, closed]
        branches:
            - main
        paths:
            - "webapp/**"
            - "api/**"
env:
    APP_LOCATION: "webapp" # location of your client code
    API_LOCATION: "api" # location of your api source code - optional
    OUTPUT_LOCATION: "build" # location of client code build output
permissions:
    issues: write
    contents: read
    pull-requests: write
jobs:
    webapp_ci:
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        name: Test
        defaults:
            run:
                working-directory: ${{ env.APP_LOCATION }}
        steps:
            - uses: actions/checkout@v4
            - name: Test
              run: npm install && npm test
    api_ci:
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        name: Test
        defaults:
            run:
                working-directory: ${{ env.API_LOCATION }}
        steps:
            - uses: actions/checkout@v4
            - name: Test
              run: npm install && npm test
    build_and_deploy:
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        name: Build and Deploy
        steps:
            - uses: actions/checkout@v4
            - name: Build And Deploy
              uses: Azure/static-web-apps-deploy@v1
              with:
                  azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  action: "upload"
                  app_location: ${{ env.APP_LOCATION }}
                  api_location: ${{ env.API_LOCATION }}
                  output_location: ${{ env.OUTPUT_LOCATION }}
