name: "GitHub Issue for TODOs"
run-name: "GitHub Issue for TODOs for commit ${{ github.sha }}"
on:
    workflow_dispatch:
        inputs:
            importAll:
                default: false
                required: false
                type: boolean
                description: Enable, if you want to import all TODOs. Runs on checked out branch! Only use if you're sure what you are doing.
    push:
        branches:
            - main
permissions:
    id-token: write
    contents: read
    issues: write
jobs:
    todos:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Run Issue Bot
              uses: derjuulsn/todo-issue@main
              with:
                  excludePattern: "^(node_modules/|.git/|dist/|build/|coverage/|bin/|obj/|.terraform/|.terraform.lock.hcl|.*\\.sln)$"
                  reopenClosed: true
                  autoAssign: false
                  label: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
